### ISSUE TITLE
Chef 13 Resource cloning deprecation support

### ISSUE THREAD

**Issue by nadobando** [sous-chefs/users#405]
### Cookbook version
5.0.0

### Chef-client version
12.20.3

### Platform Details
Centos 6

### Scenario:
**use of user_manage resource:**

Previous group[xxx]: /var/chef/cache/cookbooks/users/resources/manage.rb:58:in block (2 levels) in class_from_file
Current  group[xxx]: /var/chef/cache/cookbooks/users/resources/manage.rb:140:in `block in class_from_file at 1 location:
    - /var/chef/cache/cookbooks/users/resources/manage.rb:140:in block in class_from_file
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.

**Comment by ttdgcp** [comment]
Also seeing this on v5.1.0 across all platforms.

**Comment by mengesb** [comment]
I'm not getting these deprecation warnings in `5.3.1` with chef-client `13.8.3`

**Comment by frank-m** [comment]
Chef 13 is by now no longer supported and the cookbook is working on Chef14-16. Closing this issue.
