### ISSUE TITLE
is not creating the users only the  groups

### ISSUE THREAD

**Issue by r3k2** [sous-chefs/users#420]
### Cookbook version
latest 5.3.1

### Chef-client version
 chef-client -v
Chef: 13.8.5

### Platform Details
server is latest with ubuntu and node im testing with is centos

### Scenario:
I bootstraped and adding current users to be manage under chef.
I did not expect any changes with current users.. but it did not modify the comment information
after this Im trying to create with chef a total new user called testuser with no success
it just creates the groups

### Steps to Reproduce:
always
### Expected Result:
add new users, modify current users
### Actual Result:
nothing happens, runs and says nothing to change after the first time that added the groups.
### Extra more details.
I follow the instructions on here, on the front page.
I include the users cookbook into my made from scrach cookbook
where I include in the metadata file the users cook book

example default.rb

```
include_recipe "users"

users_manage 'mygroup' do
  group_id 2000
  search_group "mygroup"
  action [:create]
  data_bag 'MYUSERSDATABAG'
end
```
the other 2-3 groups are setup the same way with diff databags with users for that group
like I say, I am fine with the current users not been modified but new users are not getting  even created..

**Comment by ReK2Fernandez** [comment]
I'm still dealing with this, added action create inside the item in the databags, no luck
I created t he default databag users and put the people in there, no luck
I enabled :debug  searched results looking for errors... nothing.
I am starting to think is just plain ignoring the databags, like not even trying to read them.
Also I made sure the key is on /etc/chef/encrypted_data_bag_secret
I read the documentation over and over, here and on chef site... cant see what is wrong..

**Comment by jkovarick** [comment]
I'm also encountering this issue.

**Comment by mateuszkwiatkowski** [comment]
I had similar problem and resolved it by reindexing data on chef-server:
```
chef-server-ctl reindex --all-orgs
```
