### ISSUE TITLE
Removal of users fails when action set to remove in databag

### ISSUE THREAD

**Issue by sjsadowski** [sous-chefs/users#422]
### Cookbook version
5.3.1

### Chef-client version
14.1.12

### Platform Details
CentOS 7.5

### Scenario:
Remove users

### Steps to Reproduce:
Change an action for a user's databag to 'remove'

### Expected Result:
User is removed

### Actual Result:
Nothing; user is not removed - action seems to be ignored.

**Comment by TyMac** [comment]
Have the same issue on chef-client 13.6.4 - CentOS 7.4 and 7.5

**Comment by clarkdave** [comment]
Not sure if this is your issue, but it's not super clear in the readme that you need to run the `:remove` action on the `users_manage` resource to actually pick up and remove users with `"action": "remove"` in the data bag:

```rb
users_manage :devops do
  group_id 2300
  action [:create, :remove]
end
```

If you run `users_manage` without specifying `action`, or just use `action [:create]`, it'll just ignore any data bag users with `action:remove`.

**Comment by sjsadowski** [comment]
Closing because this cookbook is unmaintained.
