### ISSUE TITLE
Chef-client runs fails if: 1) User account exists, and 2) User home directory does not exist, and 3) You're trying to write a ~/.ssh/authorized_keys file

### ISSUE THREAD

**Issue by fabiendelpierre** [sous-chefs/users#61]
Hi there,
I recently had an issue with chef-client runs failing when using this recipe. I don't know if you would consider it an issue but did want to bring it to your attention.

Here's what happened: my coworker and I set up an EC2 instance for testing something. We used this users cookbook to set it up, among other things. At some point, we decided to clone the server to test something else. In order to free up some space, I deleted the various user home directories, but not the user accounts.

To differentiate the cloned server from the original one, I deleted the contents of /etc/chef and generated new SSH server keys. When bootstrapping the server with Knife, using the same run list, the run fails because it can't create ~/.ssh for each user, because the parent folder doesn't exist. After manually recreating the user's home directory, the chef-client runs succeeds. At this time I can't remember if I also had to recreate the ~/.ssh directory manually before it would successfully create the authorized_keys file.
I'm guessing that if I had deleted the user accounts, none of this would have happened. So I'm guessing that if the user account exists, there is an assumption that a corresponding home directory exists, therefore the code fails if the home directory does not exist, instead of checking if it exists and creating it if it doesn't exist.

Sorry I can't provide actual error messages, the issue was fixed manually due to time constraints, I just thought about it a day or two later and came up with the above conclusions. The error message was really specific about the lack of a parent directory causing the failure.

Like I mentioned, I'm not sure whether you would think it's a feature or a problem, but I wanted to bring it up anyway. Let me know what you think, if you get the chance! Thanks!

**Comment by griffint61** [comment]
A variation on how to expose this issue: We had initially created a service account with a /dev/null home, then later decided we needed a real home. So we fixed the data bag to specify a real home instead of /dev/null. When chef-client ran it correctly updated the /etc/passwd entry but did not create the home directory. It then subsequently blew up when trying to create the .ssh subdirectory.

**Comment by jefe78** [comment]
This issue is impacting us as well. Creating the directories ahead of time solved the problem temporarily.

**Comment by nkadel-skyhook** [comment]
"usermod", which is the  account managemen tool used for changing an existing account, does not create home directories for reconfigured accounts. You can active an "ssh_keys" with empty entries to force creation of $HOME/.ssh, but yeah, it might be a good option to add.

It *can* cause chef to break if home directories are NFS mounted and the $HOME is temporarily unavailable.

**Comment by frank-m** [comment]
Currently there is a seperate directory resource that recursively creates `/home/user/.ssh` if the manage_home is true. This runs before the creation of the authorized_keys file.

As such this issue is no longer present.

I will close the issue, please reopen it if you do not agree.
