### ISSUE TITLE
Deducing nfs mounts is not sufficient for avoiding failed home directory creation

### ISSUE THREAD

**Issue by nkadel-skyhook** [sous-chefs/users#81]
The library checks 'if provided mount point is nfs' in order to prevent broken home directory cration. 

This is insufficient: if an NFS server has failed, if the relevant home directory is CIFS or gluster or attached portable storage, or autofs mounted, or a symlink to an NFS mount point, or on a failed local partition mount, etc.,  the NFS check will fail and the system will attempt to create a working home directory.

Please stop trying to insist on home directory creation. It should be a configurable and selectable attribute, and I'll be happy to try and submit a patch if it will be welcome.

**Comment by nkadel-skyhook** [comment]
This can be solved for both this ticket and #408 by activating a "manage_home" binary in the databags, rather than trying to deduce the behavior.

**Comment by frank-m** [comment]
This issue can be closed as manage_home is now by default set to false and this behaviour is no longer accurate. Please open a new issue if you still feel this needs to be addressed
